Solve VBindCover task
js-tasks-ru/vue-20211004_wowsofunny pull request #8
Opened 2022-02-02 07:51 UTC by pavelvorobev

2022-02-02 07:51 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-02-02 07:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-02-09 23:14 UTC, ShGKme requested changes
Прошу прощения, потерял ваш PR в большой очереди, и проверял больше недели...
Но небольшая правка всё-таки потребуется. Технически всё работает, но попрактикуемся ещё немного в вычисляемых свойствах, чтобы сразу привязать фон к нужному значению без дублирования стилей с фоном.

2022-02-09 23:14 UTC, ShGKme commented on 03-sfc/01-VBindCover/components/MeetupCover.vue
> +}
Вместо добавления нового класса с дублированием стиля фона (включая длинное значение с градиентом), требуется вычислить полностью второй фон при привязке. Это можно сделать тернарником прямо в v-bind, где сейчас ``'`url(${image})`'``, но лучше вынести это в вычисляемое свойство, где будет возвращаться либо `url`, либо `var` с фоном по умолчанию.

2022-02-10 07:17 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-10 08:07 UTC, ShGKme approved these changes
Все задачи приняты 👍

2022-02-10 08:08 UTC, merged